%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTimerEvent
%% Source: /net/isildur/ldisk/daily_build/r15b03_prebuild_opu_o.2012-12-06_18/otp_src_R15B03/lib/cosTime/src/CosTimerEvent.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIMEREVENT_HRL).
-define(COSTIMEREVENT_HRL, true).


-record('CosTimerEvent_TimerEventT', {utc, event_data}).


-endif.


