%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventDomainAdmin_EventDomainFactory
%% Source: /net/isildur/ldisk/daily_build/r15b03_prebuild_opu_o.2012-12-06_18/otp_src_R15B03/lib/cosEventDomain/src/CosEventDomainAdmin.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTDOMAINADMIN_EVENTDOMAINFACTORY_HRL).
-define(COSEVENTDOMAINADMIN_EVENTDOMAINFACTORY_HRL, true).




-endif.


