%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTransactions_Inactive
%% Source: /net/isildur/ldisk/daily_build/r15b03_prebuild_opu_o.2012-12-06_18/otp_src_R15B03/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTransactions_Inactive').
-ic_compiled("4_2_31").


-include("CosTransactions.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTransactions/Inactive:1.0","Inactive",[]}.

%% returns id
id() -> "IDL:omg.org/CosTransactions/Inactive:1.0".

%% returns name
name() -> "CosTransactions_Inactive".



