%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_SubtransactionAwareResource
%% Source: /net/isildur/ldisk/daily_build/r15b03_prebuild_opu_o.2012-12-06_18/otp_src_R15B03/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_SUBTRANSACTIONAWARERESOURCE_HRL).
-define(COSTRANSACTIONS_SUBTRANSACTIONAWARERESOURCE_HRL, true).




-endif.


