%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosTransactions
%% Source: /net/isildur/ldisk/daily_build/r15b03_prebuild_opu_o.2012-12-06_18/otp_src_R15B03/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSTRANSACTIONS_HRL).
-define(OE_COSTRANSACTIONS_HRL, true).




-endif.


