%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm_PullConsumer
%% Source: /net/isildur/ldisk/daily_build/r15b03_prebuild_opu_o.2012-12-06_18/otp_src_R15B03/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_PULLCONSUMER_HRL).
-define(COSEVENTCOMM_PULLCONSUMER_HRL, true).




-endif.


