%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_SequencePullSupplier
%% Source: /net/isildur/ldisk/daily_build/r15b03_prebuild_opu_o.2012-12-06_18/otp_src_R15B03/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_SEQUENCEPULLSUPPLIER_HRL).
-define(COSNOTIFYCOMM_SEQUENCEPULLSUPPLIER_HRL, true).




-endif.


