%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyFilter_MappingFilter
%% Source: /net/isildur/ldisk/daily_build/r15b03_prebuild_opu_o.2012-12-06_18/otp_src_R15B03/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYFILTER_MAPPINGFILTER_HRL).
-define(COSNOTIFYFILTER_MAPPINGFILTER_HRL, true).




-endif.


