%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_EventChannelFactory
%% Source: /net/isildur/ldisk/daily_build/r15b03_prebuild_opu_o.2012-12-06_18/otp_src_R15B03/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.2.31
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_EVENTCHANNELFACTORY_HRL).
-define(COSNOTIFYCHANNELADMIN_EVENTCHANNELFACTORY_HRL, true).




-endif.


